# Importing the libraries

In [ ]:
import numpy as np

# Generating code vector from given message bits

## Creating identity matrix of size kxk 
##       where k is length of message bits

In [ ]:
iden = np.identity(3)
print(iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Creating parity matrix using user input parity bits

In [ ]:
r, c = map(int, input().split()) # taking number of rows and column
p = np.array([input().strip().split() for _ in range(r)], int)

3 3
1 1 1
1 1 0
1 0 1


In [ ]:
print(p)

[[1 1 1]
 [1 1 0]
 [1 0 1]]


## Creating generator matrix 
## [G] = [I:P]

In [ ]:
g = np.concatenate((iden, p), axis = 1)
print(g)

[[1. 0. 0. 1. 1. 1.]
 [0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0. 1.]]


## Getting message vector from user

In [ ]:
m = list(map(int,input().split())) # Input as list

1 0 1


In [ ]:
m = np.asarray(m) # Converting list to numpy array
print(m)

[1 0 1]


## Generating code vector
## [C] = [M] . [G]

In [ ]:
c = m.dot(g) % 2 # Mod 2 to preserve binary nature of code

In [ ]:
print(c)

[1. 0. 1. 0. 1. 0.]


# Error detection for received code vector


## Getting received code vector from user

In [ ]:
print("Enter received code vector")
r = list(map(int,input().split())) # Input as list

Enter received code vector
1 1 1 0 1 0


In [ ]:
r = np.asarray(r) # Converitng to numpy array
print(r)

[1 1 1 0 1 0]


## Creating Parity matric [H]
## [H] = [Ptranspose:I]


In [ ]:
h = np.concatenate((np.transpose(p), iden), axis = 1)

## Obtaining syndrome matrix as Htranspose

In [ ]:
syndrome = np.transpose(h)
print(syndrome)

[[1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Obtaining received code vector from received code
## [R_code] = [R] . [Htranspose]

In [ ]:
r_code = r.dot(syndrome) % 2 # Mod 2 to preserve binary nature

In [ ]:
print(r_code) # Printing syndrome

[1. 1. 0.]


## Error checking: is syndrome = 0?


In [ ]:
is_all_zero = np.all((r_code == 0))

In [ ]:
if is_all_zero :
  print("No error")
else:
  print("Error is present")

Error is present
